# --------------------------|
# Tradechest configuration  |
# --------------------------|

# names:   https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# range    renderdistance in blocks
# qty:     quantity to spawn
# speed:   flyingspeed of the particles
# height:  height-offset
# delay:   delay to the next particle-update in ticks
particle:
  name: VILLAGER_HAPPY
  range: 20
  qty: 6
  speed: 0
  height: 0.9
  delay: 25

# The tradechest item.
# Changes here will make older items no longer work.
item:
  name: Tradechest
  lore:
  - This special chest can
  - be opened by everyone.


# The messages used by the plugin.
message:
  helptext:     "§7/tradechest (info | reload | item | help)"
  infoHeadLine: "§7--- Tradechest info ---"
  showRadius:   "§7Particle radius: §f"
  totalChest:   "§7Chests loaded: §f"
  loadedChest:  "§7Chests active: §f"
  reload:       "§aTradechest configuration reloaded."
  gotItem:      "§aTradechest received."
  placedItem:   "§aTradechest placed."
  loadWorldFail: "World with tradechest could not be found/loaded: "
