# --------------------------|
# Tradechest Konfiguration  |
# --------------------------|

# name:   https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# range   Sichtweite in Blöcken.
# qty:    Anzahl der Partikel
# speed:  Bewegungsgeschwindigkeit der Partikel
# height: Spawnhöhe der Partikel.
# delay:  Wartezeit zum nächsten Partikelupdate in Ticks.
particle:
  name: VILLAGER_HAPPY
  range: 20
  qty: 6
  speed: 0
  height: 0.9
  delay: 25

# Das Tauschkisten Item.
# Durch Änderungen hier werden alte Items nicht mehr erkannt.
item:
  name: Tauschkiste
  lore:
  - Diese besondere Kiste kann
  - jeder Spieler öffnen.


# Alle genutzen Nachrichten.
message:
  helptext:     "§7/tradechest (info | reload | item | help)"
  infoHeadLine: "§7--- Tradechest info ---"
  showRadius:   "§7Partikel Radius: §f"
  totalChest:   "§7Geladene Kisten: "§f"
  loadedChest:  "§7Aktive Kisten: §f"
  reload:       "§aTradechest Konfiguration neu geladen."
  gotItem:      "§aTauschkiste erhalten."
  placedItem:   "§aTauschkiste plaziert."
  loadWorldFail: "Welt mit Tauschkisten konnte nicht gefunden/geladen werden: "
