name: Tradechest
version: 1.0
author: BloodEko
main: de.tradechest.TradechestPlugin
commands:
  tradechest:
      description: 'Tradechest administration.'
      permission: tradechest.admin
      permission-message: You do not have permission!
      usage: /<command> help